### ISSUE TITLE
Add explicit names to all CI workflow checks + tweak branch protection rules

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/chainlink-terra#238]
Notice: there are no names for defined checks so it's hard to figure out what checks do those names actually reference.

Action items:

- Add explicit names to all CI workflow checks so they are easily identifiable
- Check, tweak & improve `on:` workflow triggers in the context of branch protection rules
- Reconfigure branch protection rules as appropriate, considering both `develop` & `main` branches

**Comment by aalu1418** [comment]
addressed in: https://github.com/smartcontractkit/chainlink-terra/pull/241
